services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: minitorrent
      MYSQL_USER: minitorrentuser
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_TCP_PORT: 3307
    secrets:
      - db_root_password
      - db_password

  app:
    depends_on:
      - db
    image: golang:latest
    build:
      context: .
      dockerfile: Web.Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3307
      DB_USER: minitorrentuser
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: minitorrent
    ports:
      - "8080:8080"
    secrets:
      - db_password

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

volumes:
  db_data: